In [1]:
import pandas as pd

data = {
    "player":           ["Babar", "Rizwan", "Babar", "Fakhar", "Rizwan", "Babar", "Fakhar", "Rizwan"],
    "opposition":       ["India", "Australia", "England", "India", "England", "Australia", "England", "India"],
    "batting_position": [3, 1, 3, 2, 1, 3, 2, 1],
    "balls":            [30, 50, 15, 60, 28, 3, 70, 40],
    "fours":            [5, 8, 1, 10, 3, 0, 12, 4],
    "sixes":            [1, 2, 0, 4, 1, 0, 3, 2],
    "runs":             [45, 67, 12, 89, 34, 0, 102, 51],
}

df = pd.DataFrame(data)
df

   player opposition  batting_position  balls  fours  sixes  runs
0   Babar      India                 3     30      5      1    45
1  Rizwan  Australia                 1     50      8      2    67
2   Babar    England                 3     15      1      0    12
3  Fakhar      India                 2     60     10      4    89
4  Rizwan    England                 1     28      3      1    34
5   Babar  Australia                 3      3      0      0     0
6  Fakhar    England                 2     70     12      3   102
7  Rizwan      India                 1     40      4      2    51

In [2]:
df.head(3)

   player opposition  batting_position  balls  fours  sixes  runs
0   Babar      India                 3     30      5      1    45
1  Rizwan  Australia                 1     50      8      2    67
2   Babar    England                 3     15      1      0    12

In [3]:
df.shape

(8, 7)

In [4]:
df.columns

Index(['player', 'opposition', 'batting_position', 'balls', 'fours', 'sixes',
       'runs'],
      dtype='str')

In [5]:
df.dtypes

player                str
opposition            str
batting_position    int64
balls               int64
fours               int64
sixes               int64
runs                int64
dtype: object

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   player            8 non-null      str
 1   opposition        8 non-null      str
 2   batting_position  8 non-null      int64
 3   balls             8 non-null      int64
 4   fours             8 non-null      int64
 5   sixes             8 non-null      int64
 6   runs              8 non-null      int64
dtypes: int64(5), str(2)
memory usage: 580.0 bytes

In [7]:
df.describe()

       batting_position      balls      fours     sixes       runs
count           8.00000   8.000000   8.000000  8.000000    8.00000
mean            2.00000  37.000000   5.375000  1.625000   50.00000
std             0.92582  22.570524   4.274091  1.407886   35.33513
min             1.00000   3.000000   0.000000  0.000000    0.00000
25%             1.00000  24.750000   2.500000  0.750000   28.50000
50%             2.00000  35.000000   4.500000  1.500000   48.00000
75%             3.00000  52.500000   8.500000  2.250000   72.50000
max             3.00000  70.000000  12.000000  4.000000  102.00000

In [8]:
print(df["runs"])
print(type(df["runs"]))

0     45
1     67
2     12
3     89
4     34
5      0
6    102
7     51
Name: runs, dtype: int64
<class 'pandas.Series'>

In [9]:
df[["player", "runs"]]

   player  runs
0   Babar    45
1  Rizwan    67
2   Babar    12
3  Fakhar    89
4  Rizwan    34
5   Babar     0
6  Fakhar   102
7  Rizwan    51

In [10]:
print(df["runs"].mean())
print(df["sixes"].max())

50.0
4

In [11]:
df["strike_rate"] = df["runs"] / df["balls"] * 100
df

   player opposition  batting_position  balls  fours  sixes  runs  strike_rate
0   Babar      India                 3     30      5      1    45   150.000000
1  Rizwan  Australia                 1     50      8      2    67   134.000000
2   Babar    England                 3     15      1      0    12    80.000000
3  Fakhar      India                 2     60     10      4    89   148.333333
4  Rizwan    England                 1     28      3      1    34   121.428571
5   Babar  Australia                 3      3      0      0     0     0.000000
6  Fakhar    England                 2     70     12      3   102   145.714286
7  Rizwan      India                 1     40      4      2    51   127.500000

In [12]:
X = df[["balls", "fours", "sixes"]]
y = df["runs"]

print(X.shape)
print(y.shape)

(8, 3)
(8,)

In [13]:
# 1. Shape (hardcode kiye bina)
rows, columns = df.shape
print(f"Innings: {rows}, Columns: {columns}")

Innings: 8, Columns: 8

In [14]:
# 2. Data types
print(df.dtypes)

# Numerical:   balls, fours, sixes, runs, strike_rate
# Categorical: player, opposition
#
# batting_position int64 mein store hai, lekin asal mein CATEGORICAL (ordinal) hai.
# "Average batting position 2.0" ka koi matlab nahi; ye numbers sirf labels hain.
# (Har position pe player ke average RUNS nikalna meaningful hai, wo groupby se karenge.)
#
# Sabaq: dtype batata hai data KAISE store hua hai,
#        column ASAL mein kya hai, ye domain knowledge decide karta hai.

player                  str
opposition              str
batting_position      int64
balls                 int64
fours                 int64
sixes                 int64
runs                  int64
strike_rate         float64
dtype: object

In [15]:
# 3. Mean vs median
print(f"Runs Mean:   {df['runs'].mean()}")
print(f"Runs Median: {df['runs'].median()}")

# Mean (50) median (48) se zyada hai kyunki 102 jaisa bara score
# mean ko upar kheench leta hai. Median sirf beech ki values (45, 51) dekhta hai,
# isliye outliers ka us pe asar nahi hota.

Runs Mean:   50.0
Runs Median: 48.0

In [16]:
# 4. Naye features
df["boundary_runs"] = df["fours"] * 4 + df["sixes"] * 6
df["boundary_pct"] = df["boundary_runs"] / df["runs"] * 100

# Index 5 (duck): runs = 0, to 0/0 = NaN (missing value).
# Pandas error nahi deta, chupke se NaN rakh deta hai.
# Feature engineering khud bhi missing values paida kar sakti hai.
df

,player,opposition,batting_position,balls,fours,sixes,runs,strike_rate,boundary_runs,boundary_pct
0,Babar,India,3,30,5,1,45,150.000000,26,57.777778
1,Rizwan,Australia,1,50,8,2,67,134.000000,44,65.671642
2,Babar,England,3,15,1,0,12,80.000000,4,33.333333
3,Fakhar,India,2,60,10,4,89,148.333333,64,71.910112
4,Rizwan,England,1,28,3,1,34,121.428571,18,52.941176
5,Babar,Australia,3,3,0,0,0,0.000000,0,NaN
6,Fakhar,England,2,70,12,3,102,145.714286,66,64.705882
7,Rizwan,India,1,40,4,2,51,127.500000,28,54.901961

In [17]:
# 5. X aur y
X = df[["balls", "fours", "sixes", "batting_position"]]
y = df["runs"]

print(f"X shape: {X.shape}")
print(f"y shape: {y.shape}")

# ⚠️ DATA LEAKAGE: agar prediction innings SE PEHLE karni hai, to
# balls, fours, sixes sab innings ke BAAD pata chalte hain.
# Model asal mein runs ≈ 4*fours + 6*sixes seekh lega, aur real prediction
# ke waqt ye values maujood hi nahi hongi.
#
# Pre-innings ke theek features: batting_position, opposition, venue,
# recent form (pichli innings ka average), career average.

X shape: (8, 4)
y shape: (8,)