# Lesson 2.1: Pandas, Series aur DataFrame

## Pandas kyun?
NumPy ke do masle:
1. Columns ke **naam nahi**: yaad rakhna parta tha ke `X[:, 1]` fours hai
2. **Text** (player, opposition) achha nahi chalta

| | NumPy | Pandas |
|---|---|---|
| Column ke naam | ❌ `X[:, 1]` | ✅ `df["fours"]` |
| Numbers + text ek saath | ❌ | ✅ |
| CSV, missing values, grouping | mushkil | ek line |

Do cheezein yaad rakhein:
- **DataFrame** = poora table (MySQL table jaisa)
- **Series** = us table ka **ek column**

Andar se Pandas, NumPy hi use karta hai, to vectorisation aur mask sab yahan bhi chalte hain.

In [1]:
import pandas as pd

---
## Part 1: DataFrame banana

Dictionary: har **key = column ka naam**, har **value = us column ki list**. Saari lists ki length barabar (8 innings).

Aakhri line pe sirf `df` likha hai, `print(df)` nahi. Notebook **cell ki aakhri line** khud dikhati hai, aur DataFrame **saaf table** ki shakal mein aata hai.

In [2]:
data = {
    "player":           ["Babar", "Rizwan", "Babar", "Fakhar", "Rizwan", "Babar", "Fakhar", "Rizwan"],
    "opposition":       ["India", "Australia", "England", "India", "England", "Australia", "England", "India"],
    "batting_position": [3, 1, 3, 2, 1, 3, 2, 1],
    "balls":            [30, 50, 15, 60, 28, 3, 70, 40],
    "fours":            [5, 8, 1, 10, 3, 0, 12, 4],
    "sixes":            [1, 2, 0, 4, 1, 0, 3, 2],
    "runs":             [45, 67, 12, 89, 34, 0, 102, 51],
}

df = pd.DataFrame(data)
df

   player opposition  batting_position  balls  fours  sixes  runs
0   Babar      India                 3     30      5      1    45
1  Rizwan  Australia                 1     50      8      2    67
2   Babar    England                 3     15      1      0    12
3  Fakhar      India                 2     60     10      4    89
4  Rizwan    England                 1     28      3      1    34
5   Babar  Australia                 3      3      0      0     0
6  Fakhar    England                 2     70     12      3   102
7  Rizwan      India                 1     40      4      2    51

---
## Part 2: Har naye dataset pe pehle ye 6 commands

| Command | Kya batata hai |
|---|---|
| `df.head(3)` | pehli 3 rows (`tail()` = aakhri) |
| `df.shape` | `(rows, columns)`, NumPy jaisa |
| `df.columns` | columns ke naam |
| `df.dtypes` | har column ka type |
| `df.info()` | sab ek saath + **kitni values missing** |
| `df.describe()` | numeric columns ki statistics |

In [3]:
df.head(3)

   player opposition  batting_position  balls  fours  sixes  runs
0   Babar      India                 3     30      5      1    45
1  Rizwan  Australia                 1     50      8      2    67
2   Babar    England                 3     15      1      0    12

In [4]:
df.shape   # (8, 7)

(8, 7)

In [5]:
df.columns

Index(['player', 'opposition', 'batting_position', 'balls', 'fours', 'sixes',
       'runs'],
      dtype='str')

In [6]:
df.dtypes

player                str
opposition            str
batting_position    int64
balls               int64
fours               int64
sixes               int64
runs                int64
dtype: object

- `int64` = poore numbers · `float64` = decimal numbers
- `str` = text. (Pandas 3.0 mein `str` dikhta hai; purane tutorials mein `object` likha hota hai. Matlab same: **text / categorical**.)

In [7]:
df.info()   # sab columns "8 non-null" → kuch missing nahi

<class 'pandas.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   player            8 non-null      str
 1   opposition        8 non-null      str
 2   batting_position  8 non-null      int64
 3   balls             8 non-null      int64
 4   fours             8 non-null      int64
 5   sixes             8 non-null      int64
 6   runs              8 non-null      int64
dtypes: int64(5), str(2)
memory usage: 580.0 bytes

### `describe()` — sirf `runs` column pe samjhein

Sorted runs:
```
0   12  │  34   45  │  51   67  │  89   102
        ↑           ↑           ↑
      28.5         48         72.5
      (25%)       (50%)       (75%)
```

| Row | runs | Matlab |
|---|---|---|
| count | 8 | 8 values maujood (koi missing nahi) |
| mean | 50 | average: 400 ÷ 8 |
| std | 35.3 | scores average se ~±35 upar neeche |
| min / max | 0 / 102 | sab se kam / zyada |
| 25% | 28.5 | 25% innings is se **kam** |
| **50%** | **48** | **median**, beech wala score = (45+51)/2 |
| 75% | 72.5 | 75% innings is se kam |

**Beech wali 50% innings 28.5 aur 72.5 ke darmiyan** hain (ye range **IQR** hai, outliers mein kaam aati hai).

In [8]:
df.describe()

       batting_position      balls      fours     sixes       runs
count           8.00000   8.000000   8.000000  8.000000    8.00000
mean            2.00000  37.000000   5.375000  1.625000   50.00000
std             0.92582  22.570524   4.274091  1.407886   35.33513
min             1.00000   3.000000   0.000000  0.000000    0.00000
25%             1.00000  24.750000   2.500000  0.750000   28.50000
50%             2.00000  35.000000   4.500000  1.500000   48.00000
75%             3.00000  52.500000   8.500000  2.250000   72.50000
max             3.00000  70.000000  12.000000  4.000000  102.00000

### `describe()` se 4 professional sawal
1. **`count` sab columns mein barabar?** Kam ho to **missing values** hain
2. **`min`/`max` sense banate hain?** −5 balls ya 900 runs = ghalti (**sanity check**, cricket knowledge)
3. **Mean aur median mein kitna farq?** Bohat zyada = bare scores (outliers) average kheench rahe hain
4. **Kya ye statistic us column ke liye matlab rakhti hai?** `batting_position` ka mean **2.0**: "average position 2" ka koi matlab nahi (Part 6 mein)

Text column ka describe alag hota hai (`count`, `unique`, `top`, `freq`):

In [9]:
df["player"].describe()

count         8
unique        3
top       Babar
freq          3
Name: player, dtype: object

**std ka chhota farq:** Pandas ka `std` (35.33) **sample** std hai (n − 1 se divide), NumPy ka `.std()` **population** std (n se). Numbers thore alag aayein to pareshan na hon.

---
## Part 3: Columns select karna

| Code | Result | Shape |
|---|---|---|
| `df["runs"]` | **Series** (ek column) | `(8,)` 1D |
| `df[["runs"]]` | **DataFrame** (ek column wala table) | `(8, 1)` 2D |
| `df[["player", "runs"]]` | **DataFrame** (do columns) | `(8, 2)` |

**Single bracket = 1D, double bracket = 2D.** Bilkul NumPy wala farq.

In [10]:
print(df["runs"])
print(type(df["runs"]))

0     45
1     67
2     12
3     89
4     34
5      0
6    102
7     51
Name: runs, dtype: int64
<class 'pandas.Series'>

In [24]:
print(df["runs"].shape)     # (8,)   → 1D
print(df[["runs"]].shape)   # (8, 1) → 2D

(8,)
(8, 1)

In [12]:
df[["player", "runs"]]

   player  runs
0   Babar    45
1  Rizwan    67
2   Babar    12
3  Fakhar    89
4  Rizwan    34
5   Babar     0
6  Fakhar   102
7  Rizwan    51

In [13]:
print(df["runs"].mean())
print(df["sixes"].max())

50.0
4

---
## Part 4: Naya column (feature engineering)
Vectorisation, NumPy jaisa, bas ab column ke **naam** se.

In [14]:
df["strike_rate"] = df["runs"] / df["balls"] * 100
df

   player opposition  batting_position  balls  fours  sixes  runs  strike_rate
0   Babar      India                 3     30      5      1    45   150.000000
1  Rizwan  Australia                 1     50      8      2    67   134.000000
2   Babar    England                 3     15      1      0    12    80.000000
3  Fakhar      India                 2     60     10      4    89   148.333333
4  Rizwan    England                 1     28      3      1    34   121.428571
5   Babar  Australia                 3      3      0      0     0     0.000000
6  Fakhar    England                 2     70     12      3   102   145.714286
7  Rizwan      India                 1     40      4      2    51   127.500000

---
## Part 5: X aur y
- **X** → double brackets → 2D table (features)
- **y** → single bracket → 1D (target)
- X ki rows = y ki length → **aligned**

In [15]:
X = df[["balls", "fours", "sixes"]]
y = df["runs"]

print(X.shape)   # (8, 3)
print(y.shape)   # (8,)

(8, 3)
(8,)

---
## Part 6: Exercise ke jawab

### 1. Shape (hardcode kiye bina)
`rows, columns = df.shape` = tuple ko seedha do variables mein **unpack** karna.

In [16]:
rows, columns = df.shape
print(f"Innings: {rows}, Columns: {columns}")   # strike_rate ke baad 8 columns

Innings: 8, Columns: 8

⚠️ Ye cell **dobara** chalayein (neeche ke cells ke baad) to `Columns: 10` aayega, kyunki aage 2 columns aur jurte hain. Notebook **run hone ka order** dekhti hai.

### 2. Numerical vs categorical

In [17]:
df.dtypes

player                  str
opposition              str
batting_position      int64
balls                 int64
fours                 int64
sixes                 int64
runs                  int64
strike_rate         float64
dtype: object

| Numerical (maths matlab rakhta hai) | Categorical (labels / groups) |
|---|---|
| balls, fours, sixes, runs, strike_rate | player, opposition |

### `batting_position`: number hai, lekin asal mein **categorical (ordinal)**

In [18]:
df["batting_position"].mean()   # 2.0 → "average batting position 2"?? koi matlab nahi

np.float64(2.0)

- No. 3, opener (No. 1) se **"teen guna"** nahi hota. Ye numbers sirf **label** hain
- Order hai (top order → middle → tail), isliye **ordinal**
- Har position pe player ke **average runs** nikalna meaningful hai (groupby, Lesson 2.3)

> **dtype** batata hai data **kaise store** hua. Column **asal mein kya hai**, ye **domain knowledge** decide karta hai.

### 3. Mean vs median

In [19]:
print(f"Runs Mean:   {df['runs'].mean()}")
print(f"Runs Median: {df['runs'].median()}")

Runs Mean:   50.0
Runs Median: 48.0

Mean (50) median (48) se zyada kyunki **102** mean ko upar kheenchta hai. Median sirf beech (45, 51) dekhta hai.
Agar 102 ki jagah 200 hota: median **phir bhi 48**, mean **62**. Isi liye outliers ho to **median** zyada bharosemand (Ames mein median imputation isi wajah se).

### 4. Naye features: boundary_runs aur boundary_pct

In [20]:
df["boundary_runs"] = df["fours"] * 4 + df["sixes"] * 6
df["boundary_pct"] = df["boundary_runs"] / df["runs"] * 100
df

,player,opposition,batting_position,balls,fours,sixes,runs,strike_rate,boundary_runs,boundary_pct
0,Babar,India,3,30,5,1,45,150.000000,26,57.777778
1,Rizwan,Australia,1,50,8,2,67,134.000000,44,65.671642
2,Babar,England,3,15,1,0,12,80.000000,4,33.333333
3,Fakhar,India,2,60,10,4,89,148.333333,64,71.910112
4,Rizwan,England,1,28,3,1,34,121.428571,18,52.941176
5,Babar,Australia,3,3,0,0,0,0.000000,0,NaN
6,Fakhar,England,2,70,12,3,102,145.714286,66,64.705882
7,Rizwan,India,1,40,4,2,51,127.500000,28,54.901961

Index 5 (Babar ka **duck**): runs = 0, boundary = 0 → `0 / 0` = **NaN**.
- Normal Python mein `0/0` = `ZeroDivisionError`. Pandas **error nahi deta**, chupke se NaN rakh deta hai
- **Feature engineering khud bhi missing values paida kar sakti hai**

In [21]:
df["boundary_pct"].isnull().sum()   # 1

np.int64(1)

(Isay theek karna Lesson 2.2 mein: `df.loc[df["runs"] == 0, "boundary_pct"] = 0`)

### 5. X aur y (4 features)

In [22]:
X = df[["balls", "fours", "sixes", "batting_position"]]
y = df["runs"]

print(f"X shape: {X.shape}")   # (8, 4)
print(f"y shape: {y.shape}")   # (8,)

X shape: (8, 4)
y shape: (8,)

---
## Part 7: Data leakage (sab se important sabaq)

Har ML project ka pehla sawal:
> **"Prediction KIS WAQT ho rahi hai?"**

Agar **innings se pehle** predict karna hai: `balls`, `fours`, `sixes` sab innings **ke baad** pata chalte hain.
Model asal mein ye seekhega:
```
runs ≈ 4 × fours + 6 × sixes + (baaqi singles/doubles)
```
Yaani **jawab ka hissa pehle se dekh ke** jawab. Training/testing mein accuracy zabardast, lekin asal prediction ke waqt ye values **hain hi nahi** → model bekaar.

| Prediction kab? | Theek features | Leakage |
|---|---|---|
| **Innings se pehle** | batting position, opposition, venue, recent form, career average | balls, fours, sixes, strike_rate, out kaise hua |
| **Innings ke beech** (10 overs baad) | upar wale + ab tak ki balls, runs, wickets, run rate | final balls, final fours |

> Jab koi feature target se **"bohat achha"** jura ho, khush hone se pehle poochein: **ye value KAB pata chalti hai?**

---
## Khulasa
| Kaam | Code |
|---|---|
| Table banana | `pd.DataFrame(dict)` |
| Pehli nazar | `head`, `shape`, `columns`, `dtypes`, `info`, `describe` |
| Ek column (1D) | `df["col"]` |
| Kai columns (2D) | `df[["a", "b"]]` |
| Naya column | `df["new"] = df["a"] / df["b"]` |
| X / y | `X = df[[...]]`, `y = df["target"]` |