In [1]:
import pandas as pd

data = {
    "player":           ["Babar", "Rizwan", "Babar", "Fakhar", "Rizwan", "Babar", "Fakhar", "Rizwan"],
    "opposition":       ["India", "Australia", "England", "India", "England", "Australia", "England", "India"],
    "batting_position": [3, 1, 3, 2, 1, 3, 2, 1],
    "balls":            [30, 50, 15, 60, 28, 3, 70, 40],
    "fours":            [5, 8, 1, 10, 3, 0, 12, 4],
    "sixes":            [1, 2, 0, 4, 1, 0, 3, 2],
    "runs":             [45, 67, 12, 89, 34, 0, 102, 51],
}

df = pd.DataFrame(data)
df

   player opposition  batting_position  balls  fours  sixes  runs
0   Babar      India                 3     30      5      1    45
1  Rizwan  Australia                 1     50      8      2    67
2   Babar    England                 3     15      1      0    12
3  Fakhar      India                 2     60     10      4    89
4  Rizwan    England                 1     28      3      1    34
5   Babar  Australia                 3      3      0      0     0
6  Fakhar    England                 2     70     12      3   102
7  Rizwan      India                 1     40      4      2    51

In [5]:
df.iloc[0]        
df.iloc[0:3]          # rows 0, 1, 2    # pehli row
df.iloc[2, 6]         # row 2, column 6
df.iloc[:, 0:2]       # saari rows, pehle 2 columns

   player opposition
0   Babar      India
1  Rizwan  Australia
2   Babar    England
3  Fakhar      India
4  Rizwan    England
5   Babar  Australia
6  Fakhar    England
7  Rizwan      India

In [10]:
df.loc[0, "runs"]                      # row 0 ke runs
df.loc[0:3, ["player", "runs"]]        # rows 0 se 3, do columns

   player  runs
0   Babar    45
1  Rizwan    67
2   Babar    12
3  Fakhar    89

In [18]:
df[df["runs"] >= 50]

df[df["player"] == "Babar"]

df[(df["opposition"] == "India") & (df["runs"] >= 50)]

df[df["opposition"].isin(["India", "Australia"])]

df.loc[df["runs"] >= 50, ["player", "opposition", "runs"]]

   player opposition  runs
1  Rizwan  Australia    67
3  Fakhar      India    89
6  Fakhar    England   102
7  Rizwan      India    51

In [20]:
df.sort_values("runs", ascending=False)

df.sort_values("runs", ascending=False).head(3)

   player opposition  batting_position  balls  fours  sixes  runs
6  Fakhar    England                 2     70     12      3   102
3  Fakhar      India                 2     60     10      4    89
1  Rizwan  Australia                 1     50      8      2    67

In [21]:
df["boundary_runs"] = df["fours"] * 4 + df["sixes"] * 6
df["boundary_pct"] = df["boundary_runs"] / df["runs"] * 100
print(df["boundary_pct"].isnull().sum())

df.loc[df["runs"] == 0, "boundary_pct"] = 0
print(df["boundary_pct"].isnull().sum())

1
0

In [28]:
#1. Sirf Rizwan ki innings: player, opposition, runs columns ke saath.
df.loc[df["player"] == "Rizwan", ["player", "opposition", "runs"]]

#2. England ke khilaf woh innings jinmein 40 se zyada runs bane. 
df[(df["opposition"] == "England") & (df["runs"] > 40)]

#3. Openers (batting_position 1) ne kitni innings mein 50+ banaye? Sirf ginti.
len(df[(df["batting_position"] == 1) & (df["runs"] >= 50)])

#4. Sab se kam runs wali 3 innings: player aur runs.
df.sort_values("runs").head(3)[["player", "runs"]]

#5. iloc se aakhri 3 rows aur pehle 3 columns nikalein.
df.iloc[-3:, 0:3]

#6. Ek naya column fifty_plus banayein jismein True/False ho (runs ≥ 50 hain ya nahi). Phir loc use karke sirf Babar ki innings mein fifty_plus dikhayein.
df["fifty_plus"] = df["runs"] >= 50

df.loc[df["player"] == "Babar", ["player", "runs", "fifty_plus"]]

  player  runs  fifty_plus
0  Babar    45       False
2  Babar    12       False
5  Babar     0       False