# Lesson 2.2: loc, iloc, Filtering aur Sorting

Real analysis ke sawal:
- "Sirf **Babar** ki innings dikhao."
- "**India** ke khilaf **50+** scores kaun se hain?"
- "**Top 3** innings kaunsi hain?"
- "Jahan runs **0** hain, wahan `boundary_pct` ko **0** kar do."

NumPy mein mask se filtering ki thi (`runs[runs >= 50]`). Pandas mein bilkul wahi idea, bas ab **poori rows** milti hain.

| Kaam | SQL mein |
|---|---|
| Filtering | `WHERE` |
| Columns chunna | `SELECT col1, col2` |
| Sorting | `ORDER BY ... LIMIT` |
| `loc` se value badalna | `UPDATE ... SET ... WHERE` |

In [1]:
import pandas as pd

data = {
    "player":           ["Babar", "Rizwan", "Babar", "Fakhar", "Rizwan", "Babar", "Fakhar", "Rizwan"],
    "opposition":       ["India", "Australia", "England", "India", "England", "Australia", "England", "India"],
    "batting_position": [3, 1, 3, 2, 1, 3, 2, 1],
    "balls":            [30, 50, 15, 60, 28, 3, 70, 40],
    "fours":            [5, 8, 1, 10, 3, 0, 12, 4],
    "sixes":            [1, 2, 0, 4, 1, 0, 3, 2],
    "runs":             [45, 67, 12, 89, 34, 0, 102, 51],
}

df = pd.DataFrame(data)
df

   player opposition  batting_position  balls  fours  sixes  runs
0   Babar      India                 3     30      5      1    45
1  Rizwan  Australia                 1     50      8      2    67
2   Babar    England                 3     15      1      0    12
3  Fakhar      India                 2     60     10      4    89
4  Rizwan    England                 1     28      3      1    34
5   Babar  Australia                 3      3      0      0     0
6  Fakhar    England                 2     70     12      3   102
7  Rizwan      India                 1     40      4      2    51

Left side pe **0 se 7** numbers = **index**: har row ka label/ID, jaise MySQL ka primary key.

Columns ke **positions** (iloc ke liye kaam aayenge):
```
0 player | 1 opposition | 2 batting_position | 3 balls | 4 fours | 5 sixes | 6 runs
```

⚠️ Har command **alag cell** mein, kyunki notebook sirf cell ki **aakhri line** khud dikhati hai. (Purane notebook mein kai lines ek cell mein thin, isliye sirf aakhri ka output dikhta tha.)

---
## Part 1: `iloc` — position se (NumPy jaisa)
`iloc[rows, columns]`, dono **numbers** se. Slice ka end **shamil nahi** (Python jaisa).

In [2]:
df.iloc[0]          # pehli row (Series ki shakal mein)

player              Babar
opposition          India
batting_position        3
balls                  30
fours                   5
sixes                   1
runs                   45
Name: 0, dtype: object

In [3]:
df.iloc[0:3]        # rows 0, 1, 2  → 3 rows

   player opposition  batting_position  balls  fours  sixes  runs
0   Babar      India                 3     30      5      1    45
1  Rizwan  Australia                 1     50      8      2    67
2   Babar    England                 3     15      1      0    12

In [4]:
df.iloc[2, 6]       # row 2, column 6 (runs) → 12

np.int64(12)

In [5]:
df.iloc[:, 0:2]     # saari rows, pehle 2 columns (player, opposition)

   player opposition
0   Babar      India
1  Rizwan  Australia
2   Babar    England
3  Fakhar      India
4  Rizwan    England
5   Babar  Australia
6  Fakhar    England
7  Rizwan      India

In [6]:
df.iloc[-3:]        # aakhri 3 rows (negative index peeche se ginta hai)

   player opposition  batting_position  balls  fours  sixes  runs
5   Babar  Australia                 3      3      0      0     0
6  Fakhar    England                 2     70     12      3   102
7  Rizwan      India                 1     40      4      2    51

---
## Part 2: `loc` — label/naam se
`loc[rows, columns]`: rows **index label** se, columns **naam** se. Slice ka end **shamil hai**.

In [7]:
df.loc[0, "runs"]                      # row 0 ke runs → 45

np.int64(45)

In [8]:
df.loc[0:3, ["player", "runs"]]        # rows 0 SE 3 (4 rows!), do columns

   player  runs
0   Babar    45
1  Rizwan    67
2   Babar    12
3  Fakhar    89

### `iloc` vs `loc`

| | `iloc` | `loc` |
|---|---|---|
| Kis se dhoondta hai | **position** (0, 1, 2…) | **label** (index ka naam, column ka naam) |
| Columns | number: `iloc[:, 0:2]` | naam: `loc[:, ["player", "runs"]]` |
| Slice `0:3` | **3 rows** (end shamil nahi) | **4 rows** (end shamil) |

**Practical rule:** ML mein **90% waqt `loc`** aur seedha filtering. Column **naam** se kaam saaf aur mehfooz hai. `iloc` tab, jab "pehli 5 / aakhri 3 rows" jaisi position chahiye.

In [9]:
# Farq khud dekhein
print("iloc[0:3]:", len(df.iloc[0:3]), "rows")
print("loc[0:3]: ", len(df.loc[0:3]), "rows")

iloc[0:3]: 3 rows
loc[0:3]:  4 rows

---
## Part 3: Filtering

`df[df["runs"] >= 50]` do hisson mein:
```
df["runs"] >= 50     →  har row ke liye True/False (mask), NumPy jaisa
df[ mask ]           →  sirf True wali rows rakho
```

In [30]:
df["runs"] >= 50      # pehle mask khud dekhein

0    False
1     True
2    False
3     True
4    False
5    False
6     True
7     True
Name: runs, dtype: bool

In [11]:
df[df["runs"] >= 50]

   player opposition  batting_position  balls  fours  sixes  runs
1  Rizwan  Australia                 1     50      8      2    67
3  Fakhar      India                 2     60     10      4    89
6  Fakhar    England                 2     70     12      3   102
7  Rizwan      India                 1     40      4      2    51

In [12]:
df[df["player"] == "Babar"]

  player opposition  batting_position  balls  fours  sixes  runs
0  Babar      India                 3     30      5      1    45
2  Babar    England                 3     15      1      0    12
5  Babar  Australia                 3      3      0      0     0

### Do conditions
NumPy wala hi rule: `&` (and), `|` (or), aur **har condition brackets mein**.

| ❌ Ghalat | ✅ Sahi |
|---|---|
| `df["opposition"] == "India" and df["runs"] >= 50` | `(df["opposition"] == "India") & (df["runs"] >= 50)` |

In [13]:
df[(df["opposition"] == "India") & (df["runs"] >= 50)]

   player opposition  batting_position  balls  fours  sixes  runs
3  Fakhar      India                 2     60     10      4    89
7  Rizwan      India                 1     40      4      2    51

### `isin`: "inmein se koi bhi"
`(opp == "India") | (opp == "Australia")` ka chhota tareeqa. SQL: `WHERE opposition IN ('India', 'Australia')`

In [14]:
df[df["opposition"].isin(["India", "Australia"])]

   player opposition  batting_position  balls  fours  sixes  runs
0   Babar      India                 3     30      5      1    45
1  Rizwan  Australia                 1     50      8      2    67
3  Fakhar      India                 2     60     10      4    89
5   Babar  Australia                 3      3      0      0     0
7  Rizwan      India                 1     40      4      2    51

### Filter + columns ek saath: `df.loc[mask, columns]`
SQL: `SELECT player, opposition, runs FROM df WHERE runs >= 50`

In [15]:
df.loc[df["runs"] >= 50, ["player", "opposition", "runs"]]

   player opposition  runs
1  Rizwan  Australia    67
3  Fakhar      India    89
6  Fakhar    England   102
7  Rizwan      India    51

---
## Part 4: Sorting
- `sort_values("runs", ascending=False)` → zyada se kam
- `.head(3)` → **top 3**. SQL: `ORDER BY runs DESC LIMIT 3`

In [16]:
df.sort_values("runs", ascending=False)

   player opposition  batting_position  balls  fours  sixes  runs
6  Fakhar    England                 2     70     12      3   102
3  Fakhar      India                 2     60     10      4    89
1  Rizwan  Australia                 1     50      8      2    67
7  Rizwan      India                 1     40      4      2    51
0   Babar      India                 3     30      5      1    45
4  Rizwan    England                 1     28      3      1    34
2   Babar    England                 3     15      1      0    12
5   Babar  Australia                 3      3      0      0     0

In [17]:
df.sort_values("runs", ascending=False).head(3)

   player opposition  batting_position  balls  fours  sixes  runs
6  Fakhar    England                 2     70     12      3   102
3  Fakhar      India                 2     60     10      4    89
1  Rizwan  Australia                 1     50      8      2    67

In [18]:
# Shortcut: nlargest / nsmallest
df.nlargest(3, "runs")[["player", "runs"]]

   player  runs
6  Fakhar   102
3  Fakhar    89
1  Rizwan    67

---
## Part 5: `loc` se values badalna (bohat important)

Lesson 2.1 mein `boundary_pct` banaya tha. Babar ki **duck** (runs 0, boundary 0) pe `0 / 0` = **NaN** aaya.

In [19]:
df["boundary_runs"] = df["fours"] * 4 + df["sixes"] * 6
df["boundary_pct"] = df["boundary_runs"] / df["runs"] * 100

print("NaN pehle:", df["boundary_pct"].isnull().sum())   # 1
df.loc[5]   # duck wali row

NaN pehle: 1

player                  Babar
opposition          Australia
batting_position            3
balls                       3
fours                       0
sixes                       0
runs                        0
boundary_runs               0
boundary_pct              NaN
Name: 5, dtype: object

**Faisla (cricket ki soch se):** "0 runs mein 0% boundaries se aaye" → 0 kar do.

```python
df.loc[df["runs"] == 0, "boundary_pct"] = 0
```
= **"Jin rows mein runs 0 hain, unke `boundary_pct` mein 0 likh do."**
SQL: `UPDATE df SET boundary_pct = 0 WHERE runs = 0`

In [20]:
df.loc[df["runs"] == 0, "boundary_pct"] = 0
print("NaN baad:", df["boundary_pct"].isnull().sum())    # 0

NaN baad: 0

⚠️ **Ye ghalat tareeqa kabhi na likhein:**
```python
df[df["runs"] == 0]["boundary_pct"] = 0    # ❌
```
Ye pehle filter ki ek **copy** banata hai aur copy ko badalta hai, asal `df` ko nahi. Pandas 3.0 mein ye **kuch nahi badlega**.
> Values badalni hon to hamesha **`df.loc[condition, column] = value`**.

(Har NaN ka faisla 0 nahi hota. Ye yahan cricket ki mantiq se hamara faisla tha.)

---
## Part 6: Exercise ke jawab (har sawal alag cell)

### 1. Sirf Rizwan ki innings: player, opposition, runs

In [21]:
df.loc[df["player"] == "Rizwan", ["player", "opposition", "runs"]]

   player opposition  runs
1  Rizwan  Australia    67
4  Rizwan    England    34
7  Rizwan      India    51

### 2. England ke khilaf 40+ runs wali innings

In [22]:
df[(df["opposition"] == "England") & (df["runs"] > 40)]

,player,opposition,batting_position,balls,fours,sixes,runs,boundary_runs,boundary_pct
6,Fakhar,England,2,70,12,3,102,66,64.705882

Sirf Fakhar ki 102.

### 3. Openers (position 1) ne kitni innings mein 50+ banaye? Sirf ginti
Do tareeqe. Doosra NumPy wala trick: **True = 1**, to `.sum()` = ginti.

In [23]:
len(df[(df["batting_position"] == 1) & (df["runs"] >= 50)])

2

In [24]:
((df["batting_position"] == 1) & (df["runs"] >= 50)).sum()

np.int64(2)

**2** (Rizwan ke 67 aur 51).

### 4. Sab se kam runs wali 3 innings

In [25]:
df.sort_values("runs").head(3)[["player", "runs"]]

   player  runs
5   Babar     0
2   Babar    12
4  Rizwan    34

In [26]:
df.nsmallest(3, "runs")[["player", "runs"]]   # same, chhota tareeqa

   player  runs
5   Babar     0
2   Babar    12
4  Rizwan    34

### 5. iloc se aakhri 3 rows, pehle 3 columns

In [27]:
df.iloc[-3:, 0:3]

   player opposition  batting_position
5   Babar  Australia                 3
6  Fakhar    England                 2
7  Rizwan      India                 1

### 6. `fifty_plus` column (True/False), phir sirf Babar

In [28]:
df["fifty_plus"] = df["runs"] >= 50
df.loc[df["player"] == "Babar", ["player", "runs", "fifty_plus"]]

  player  runs  fifty_plus
0  Babar    45       False
2  Babar    12       False
5  Babar     0       False

Babar ki teeno innings **False** (45, 12, 0).

---
## Khulasa
| Kaam | Code |
|---|---|
| Position se | `df.iloc[rows, cols]` (end shamil nahi) |
| Naam se | `df.loc[rows, cols]` (end shamil) |
| Filter | `df[df["col"] >= x]` |
| Do conditions | `(cond1) & (cond2)`, `(cond1) \| (cond2)` |
| Kai values mein se | `df["col"].isin([...])` |
| Filter + columns | `df.loc[mask, ["a", "b"]]` |
| Sort / top N | `sort_values(..., ascending=False).head(n)`, `nlargest` |
| Value badalna | `df.loc[mask, "col"] = value` |
| Ginti | `mask.sum()` |