In [1]:
import pandas as pd

data = {
    "player":           ["Babar", "Rizwan", "Babar", "Fakhar", "Rizwan", "Babar", "Fakhar", "Rizwan"],
    "opposition":       ["India", "Australia", "England", "India", "England", "Australia", "England", "India"],
    "batting_position": [3, 1, 3, 2, 1, 3, 2, 1],
    "balls":            [30, 50, 15, 60, 28, 3, 70, 40],
    "fours":            [5, 8, 1, 10, 3, 0, 12, 4],
    "sixes":            [1, 2, 0, 4, 1, 0, 3, 2],
    "runs":             [45, 67, 12, 89, 34, 0, 102, 51],
}

df = pd.DataFrame(data)
df

   player opposition  batting_position  balls  fours  sixes  runs
0   Babar      India                 3     30      5      1    45
1  Rizwan  Australia                 1     50      8      2    67
2   Babar    England                 3     15      1      0    12
3  Fakhar      India                 2     60     10      4    89
4  Rizwan    England                 1     28      3      1    34
5   Babar  Australia                 3      3      0      0     0
6  Fakhar    England                 2     70     12      3   102
7  Rizwan      India                 1     40      4      2    51

In [2]:
df["player"].value_counts()

player
Babar     3
Rizwan    3
Fakhar    2
Name: count, dtype: int64

In [3]:
df["opposition"].value_counts()

opposition
India        3
England      3
Australia    2
Name: count, dtype: int64

In [4]:
print(df["player"].nunique())

3

In [5]:
print(df["player"].unique())

<StringArray>
['Babar', 'Rizwan', 'Fakhar']
Length: 3, dtype: str

In [6]:
df.groupby("player")["runs"].mean()

player
Babar     19.000000
Fakhar    95.500000
Rizwan    50.666667
Name: runs, dtype: float64

In [7]:
df.groupby("batting_position")["runs"].mean()

batting_position
1    50.666667
2    95.500000
3    19.000000
Name: runs, dtype: float64

In [8]:
df.groupby("player")["runs"].agg(["count", "sum", "mean", "max"])

        count  sum       mean  max
player
Babar       3   57  19.000000   45
Fakhar      2  191  95.500000  102
Rizwan      3  152  50.666667   67

In [ ]:
df.groupby(["player", "opposition"])["runs"].mean()

player  opposition
Babar   Australia       0
        England        12
        India          45
Fakhar  England       102
        India          89
Rizwan  Australia      67
        England        34
        India          51
Name: runs, dtype: int64

In [14]:
totals = df.groupby("player")[["runs", "balls"]].sum()
totals["strike_rate"] = totals["runs"] / totals["balls"] * 100
totals.sort_values("strike_rate", ascending=False)

        runs  balls  strike_rate
player
Fakhar   191    130   146.923077
Rizwan   152    118   128.813559
Babar     57     48   118.750000

In [ ]:
#1. Har opposition ke khilaf kitni innings kheli gayi?
df["opposition"].value_counts()
df.groupby("opposition").size()

#2. Har player ke total runs, zyada se kam order mein.
df.groupby("player")["runs"].sum().sort_values(ascending=False)

#3. Har opposition ke khilaf average runs. Kis team ke khilaf batting sab se mushkil rahi?
df.groupby("opposition")["runs"].mean().sort_values()

#4. Har player ki kitni innings 50+ thin? (Hint: fifty_plus column True/False hai, aur True = 1. To groupby ke baad kya lagayenge?)
df["fifty_plus"] = df["runs"] >= 50
df.groupby("player")["fifty_plus"].sum()

#5. Har player ka agg se count, mean, median aur max runs.
df.groupby("player")["runs"].agg(["count", "mean", "median", "max"])

player
Babar     0
Fakhar    2
Rizwan    2
Name: fifty_plus, dtype: int64