In [1]:
import pandas as pd

df = pd.read_csv("../data/innings.csv")
df

    match_date  player opposition    venue  batting_position  balls   runs
0   2024-01-10   Babar      India  Karachi                 3   30.0   45.0
1   2024-01-10  Rizwan      India  Karachi                 1   50.0   67.0
2   2024-01-15  Fakhar  Australia   Lahore                 2   60.0   89.0
3   2024-01-15   Babar  Australia   Lahore                 3   15.0   12.0
4   2024-01-20  Rizwan    England    Dubai                 1   28.0   34.0
5   2024-01-20  Fakhar    England    Dubai                 2    NaN   23.0
6   2024-02-02   Babar      india  Karachi                 3    3.0    0.0
7   2024-02-02  Rizwan      India  Karachi                 1   40.0   51.0
8   2024-02-02  Rizwan      India  Karachi                 1   40.0   51.0
9   2024-02-08  Fakhar    England      NaN                 2   70.0  102.0
10  2024-02-08   Babar    England   Lahore                 3   44.0  610.0
11  2024-02-15  Rizwan  Australia    Dubai                 1   35.0    NaN
12  2024-02-15   Babar  Australia    Dubai                 3  -12.0   20.0
13  2024-02-20  Fakhar      India   Lahore                 2   25.0   31.0
14  2024-02-20   Babar     India    Lahore                 3   38.0   55.0

In [2]:
df.shape

(15, 7)

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   match_date        15 non-null     str
 1   player            15 non-null     str
 2   opposition        15 non-null     str
 3   venue             14 non-null     str
 4   batting_position  15 non-null     int64
 5   balls             14 non-null     float64
 6   runs              14 non-null     float64
dtypes: float64(2), int64(1), str(4)
memory usage: 972.0 bytes

In [4]:
df.isnull().sum()

match_date          0
player              0
opposition          0
venue               1
batting_position    0
balls               1
runs                1
dtype: int64

In [5]:
df[df.isnull().any(axis=1)]

    match_date  player opposition  venue  batting_position  balls   runs
5   2024-01-20  Fakhar    England  Dubai                 2    NaN   23.0
9   2024-02-08  Fakhar    England    NaN                 2   70.0  102.0
11  2024-02-15  Rizwan  Australia  Dubai                 1   35.0    NaN

In [6]:
df.duplicated().sum()

np.int64(1)

In [16]:
df[df.duplicated(keep=False)]

   match_date  player opposition    venue  batting_position  balls  runs
7  2024-02-02  Rizwan      India  Karachi                 1   40.0  51.0
8  2024-02-02  Rizwan      India  Karachi                 1   40.0  51.0

In [17]:
df.describe()

       batting_position      balls        runs
count         15.000000  14.000000   14.000000
mean           2.066667  33.285714   85.000000
std            0.883715  21.449148  153.724529
min            1.000000 -12.000000    0.000000
25%            1.000000  25.750000   25.000000
50%            2.000000  36.500000   48.000000
75%            3.000000  43.000000   64.000000
max            3.000000  70.000000  610.000000

In [18]:
df["opposition"].value_counts()

opposition
India        5
Australia    4
England      4
india        1
India        1
Name: count, dtype: int64

In [19]:
df["opposition"].unique()

<StringArray>
['India', 'Australia', 'England', 'india', 'India ']
Length: 5, dtype: str

In [20]:
df["opposition"] = df["opposition"].str.strip().str.title()
df["opposition"].unique()

<StringArray>
['India', 'Australia', 'England']
Length: 3, dtype: str

In [21]:
print("Pehle:", df.shape)
df = df.drop_duplicates()
print("Baad:", df.shape)

Pehle: (15, 7)
Baad: (14, 7)

In [24]:
df.loc[df["balls"] < 0, "balls"] = None
df.loc[df["runs"] > 200, "runs"] = None

df.isnull().sum()
#df

match_date          0
player              0
opposition          0
venue               1
batting_position    0
balls               2
runs                2
dtype: int64

In [26]:
df = df.dropna(subset=["runs"])
df.shape
df

    match_date  player opposition    venue  batting_position  balls   runs
0   2024-01-10   Babar      India  Karachi                 3   30.0   45.0
1   2024-01-10  Rizwan      India  Karachi                 1   50.0   67.0
2   2024-01-15  Fakhar  Australia   Lahore                 2   60.0   89.0
3   2024-01-15   Babar  Australia   Lahore                 3   15.0   12.0
4   2024-01-20  Rizwan    England    Dubai                 1   28.0   34.0
5   2024-01-20  Fakhar    England    Dubai                 2    NaN   23.0
6   2024-02-02   Babar      India  Karachi                 3    3.0    0.0
7   2024-02-02  Rizwan      India  Karachi                 1   40.0   51.0
9   2024-02-08  Fakhar    England      NaN                 2   70.0  102.0
12  2024-02-15   Babar  Australia    Dubai                 3    NaN   20.0
13  2024-02-20  Fakhar      India   Lahore                 2   25.0   31.0
14  2024-02-20   Babar      India   Lahore                 3   38.0   55.0

In [27]:
df.loc[(df["match_date"] == "2024-02-08") & (df["venue"].isnull()), "venue"] = "Lahore"

In [30]:
median_balls = df["balls"].median()
print("Median balls:", median_balls)

df["balls"] = df["balls"].fillna(median_balls)
#df

Median balls: 34.0

In [31]:
print(df.isnull().sum())
print("Duplicates:", df.duplicated().sum())
print(df["opposition"].unique())
df.describe()

match_date          0
player              0
opposition          0
venue               0
batting_position    0
balls               0
runs                0
dtype: int64
Duplicates: 0
<StringArray>
['India', 'Australia', 'England']
Length: 3, dtype: str

       batting_position      balls        runs
count         12.000000  12.000000   12.000000
mean           2.166667  35.583333   44.083333
std            0.834847  18.352401   30.651882
min            1.000000   3.000000    0.000000
25%            1.750000  27.250000   22.250000
50%            2.000000  34.000000   39.500000
75%            3.000000  42.500000   58.000000
max            3.000000  70.000000  102.000000

In [32]:
df.to_csv("../data/innings_clean.csv", index=False)